# Homework 8 of group 7 
#### Members: Zhu Zhongbo, Xie Tian, Guan Zimu, Yang Zhaohua
#### This file only contains exercise1 and exercise 3

## Exercise 1
### Exercise 1 (1)

In [3]:
# cs225 assignment8 ex1

import numpy as np

# the implementation will generate a random undirected graph
def MaxSpanningTree(n, weight_range = [1, 20]):
    def __generateMAT(n):
        mat = np.random.randint(weight_range[0], weight_range[1]+1, (n, n))
        for i in range(n):
            for j in range(n):
                if i == j:
                    mat[i, j] = 0
                elif i > j:
                    mat[i, j] = mat[j, i]
        print("Cost Matrix:\n", mat, "\n")
        return mat

    # edge in form of (cost, vertex1, vertex2), where vertex1 < vertex2
    mat, edges, edges_reversed = __generateMAT(n), [], []
    sum = mat.sum()
    for i in range(n):
        for j in range(n):
            if i < j:
                edges.append((mat[i, j], i, j))
                edges_reversed.append((sum-mat[i, j], i, j))
    # Sort the edge list
    edges_reversed = sorted(edges_reversed, key=lambda x: x[0])

    for i in edges:
        print("edge: ", (i[1], i[2]), "weight: ", i[0])

    # We use index from 0 to n - 1
    CC_lst = [[i] for i in range(n)]
    MST_edges = []
    while len(CC_lst) > 1:
        curr_edge = edges_reversed.pop(0)
        for CC in CC_lst:
            if curr_edge[1] in CC:
                CC_1 = CC.copy()
            if curr_edge[2] in CC:
                CC_2 = CC
        # Merge two connected component
        if CC_1 == CC_2:
            continue
        CC_lst.remove(CC_1)
        CC_lst.remove(CC_2)
        CC_1.extend(CC_2)
        CC_lst.append(CC_1)
        MST_edges.append((curr_edge[1], curr_edge[2]))

    # Output the result
    print("\nMaxSpanningTree:\n", MST_edges)


'''
There will be no differences, both algorithms will still work.
In Kruskal's algorithm the edge added to the subset of MST is always the edge with least costs which links the two distinct components. 
It does nothing with whether the cost is positive or negative, only the comparation matters.
Similarly, in Prim's algorithm the edge added to the promising subset is also the edge with least cost, which is still revalent to the comparation and not the magnitude.
Therefore, it is still sensible.

'''


def main():
    MaxSpanningTree(4)


if __name__ == "__main__":
    main()

Cost Matrix:
 [[ 0 20  3 11]
 [20  0 13 17]
 [ 3 13  0  9]
 [11 17  9  0]] 

edge:  (0, 1) weight:  20
edge:  (0, 2) weight:  3
edge:  (0, 3) weight:  11
edge:  (1, 2) weight:  13
edge:  (1, 3) weight:  17
edge:  (2, 3) weight:  9

MaxSpanningTree:
 [(0, 1), (1, 3), (1, 2)]


### Exercise 1 (2)

There will be no differences, both algorithms will still work.
In Kruskal's algorithm the edge added to the subset of MST is always the edge with least costs which links the two distinct components. 
It does nothing with whether the cost is positive or negative, only the comparation matters.
Similarly, in Prim's algorithm the edge added to the promising subset is also the edge with least cost, which is still revalent to the comparation and not the magnitude.
Therefore, it is still sensible.


## Exercise 3


Here is the algorithm:

​	Every time when we get a new edge, check the vertices it is connected to.

​	If at least one vertices (2 or 1 vertices) does not appear in the same connected component(which must be trees) , add the edge into the graph, get the next edge and repeat the procedure.

​	If two vertices are in the same connected component, add the edge into the graph. Then there would be a loop in the connected component. Delete the edge with the biggest cost in the loop, then get the next edge and repeat the procedure.

​	Keep the procedure until there is no edge to be added in.

As in every step, we only store the edges in the MST, which contains at most $n-1$ edges, so the algorithm uses the space $O(|V|)$